FROM node:10-alpine

RUN npm install -g yarn

WORKDIR /app/assets

COPY assets/package.json assets/*yarn* ./

RUN yarn install

ENV PATH="${PATH}:/app/assets/node_modules/.bin"

CMD ["yarn", "run", "build"]
